name: Module - Documentation
on: workflow_call

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with: { enable-stack: true }
      
      # 1. Generate Haddock
      - run: stack haddock --no-haddock-deps
      - run: |
          mkdir -p documentation/static/api
          cp -r $(stack path --local-doc-root)/* documentation/static/api/

      # 2. Build Docusaurus
      - uses: actions/setup-node@v3
      - name: Build Site
        working-directory: ./documentation
        run: |
          npm ci
          npm run build

      # 3. Deploy
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build
          publish_branch: gh-pages