name: Module - Documentation
on: workflow_call

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
      
      - name: Build Haddock
        run: stack haddock --no-haddock-deps

      - name: Move API Docs to Docusaurus
        run: |
          DOC_PATH=$(stack path --local-doc-root)
          echo "Documentation found at: $DOC_PATH"
          
          ls -la "$DOC_PATH" || echo "Folder not found!"

          mkdir -p documentation/static/api

          cp -r "$DOC_PATH"/. documentation/static/api/

      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Build Site
        working-directory: ./documentation
        run: |
          npm ci
          npm run build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build
          publish_branch: gh-pages