name: Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    name: Create Release & Upload Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Haskell Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true

      - name: Build Binaries (Release Mode)
        run: |
          make

      - name: Package Binaries
        run: |
          tar -czvf glados-linux-x86_64.tar.gz glados-compiler glados-vm README.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: glados-linux-x86_64.tar.gz
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}